theme: jekyll-theme-cayman
title: EVIL LABS
description: Самые легкие лабораторные работы в мире 😂

user-settings:
  p-text-align: justify
  p-word-break: break-word
  formula-font-size: 2rem  

  pages:
    disciplines:
      modeling-of-systems: modeling-of-systems/materials.html
      object-oriented-programming: object-oriented-programming/materials.html
      software-system-architectures: software-system-architectures/materials.html
      interfaces-of-information-systems: interfaces-of-information-systems/materials.html
      
      labs:
        modeling-of-systems: modeling-of-systems/labs
        object-oriented-programming: object-oriented-programming/labs
        software-system-architectures: software-system-architectures/labs
        interfaces-of-information-systems: interfaces-of-information-systems/labs
