theme: jekyll-theme-cayman
title: EVIL LABS
description: Самые легкие лабораторные работы во вселенной 🌌 😂

user-settings:
  p-text-align: justify
  p-word-break: break-word
  li-text-align: justify
  li-word-break: break-word
  formula-font-size: 1.5rem  

  pages:
    disciplines:
      modeling-of-systems: modeling-of-systems/materials.html
      object-oriented-programming: object-oriented-programming/materials.html
      software-system-architectures: software-system-architectures/materials.html
      interfaces-of-information-systems: interfaces-of-information-systems/materials.html
      
      labs:
        modeling-of-systems: modeling-of-systems/labs
        object-oriented-programming: object-oriented-programming/labs
        software-system-architectures: software-system-architectures/labs
        interfaces-of-information-systems: interfaces-of-information-systems/labs
      
      tickets:
        modeling-of-systems: modeling-of-systems/tickets/questions.html
        object-oriented-programming: object-oriented-programming/tickets/questions.html
        software-system-architectures: software-system-architectures/tickets/questions.html
        interfaces-of-information-systems: interfaces-of-information-systems/tickets/questions.html

      files:
        modeling-of-systems: modeling-of-systems/files
        object-oriented-programming: object-oriented-programming/files
        software-system-architectures: software-system-architectures/files
        interfaces-of-information-systems: interfaces-of-information-systems/files
